### ISSUE TITLE
stringify: return `undefined` if impossible to stringify BEM notation

### ISSUE THREAD

**Issue by blond** [bem/bem-naming#55]
now need use `try..catch`:

```js
try {
    var str = bemNaming.stringify({ elem: 'elem' });
} catch(e) { /* ... */ }
```

it will be easier to check for an empty string:

```js
var str = bemNaming.stringify({ elem: 'elem' });

if (str) {
    /* ... */ 
}
```

**Comment by tadatuta** [comment]
I think semantically it should be `undefined` (like in sentence «BEM entity is undefined»)

**Comment by andrewblond** [comment]
> I think semantically it should be undefined (like in sentence «BEM entity is undefined»)

yep, it's better
