### ISSUE TITLE
parse returns undefined

### ISSUE THREAD

**Issue by eGavr** [bem/bem-naming#61]
В таких случаях

```
block_mod_mod_val
```

получаем `undefined`.

Я видел такое именование для картинок, например, такой файл

```
block_mod_modVal_blah.svg
``` 

или

```
block_mod_modVal__blah.png
```

**Comment by eGavr** [comment]
Проблема возникла при использовании [bem-walk](https://github.com/andrewblond/bem-walk/issues/8)

**Comment by andrewblond** [comment]
Привет! Это ожидаемое поведение, т.к. `block_mod_mod_val` не является валидной записью.

**Comment by eGavr** [comment]
Спасибо!
