### ISSUE TITLE
Add shortcut modifiers naming convention

### ISSUE THREAD

**Issue by delka** [bem/bem-naming#62]
Please add shortcut modifiers naming convention like `.blockName__elName.-mod_val` ie `class="blockName__elName -mod_val"`
This format is used by us at iDeus: https://github.com/ideus-team/guidelines/blob/master/frontend/bem.md and some foreign developers: http://viget.com/extend/bem-sass-modifiers

**Comment by tadatuta** [comment]
@delka BEM utilises a great idea of mixes (that's when there are different entities on same DOM node). And we are absolutely sure that BEM is not just about CSS ;)
So we need a way to tell `block-name`'s modifiers from `some-other-block`'s.
And your approach lacks this possibility. So all we can do is just to advise you not to save on matches switch to more reliable and flexible scheme.
