### ISSUE TITLE
Support baseless (BEViS) naming

### ISSUE THREAD

**Issue by zxqfox** [bem/bem-naming#64]
Since there are:
- https://github.com/azproduction/b_ (which does it in similar way)
- https://github.com/bem/bh/pull/134/files — support is already in BH 4.0

etc.

**Comment by tadatuta** [comment]
no way!

**Comment by blond** [comment]
This is still is actual?

**Comment by tadatuta** [comment]
my comment is still actual ;)

**Comment by blond** [comment]
If it's really necessary for someone, I would like to know why ;)

**Comment by tadatuta** [comment]
let these people create their own package )

**Comment by blond** [comment]
well, if someone will need it, then he will be able to create one more issue
