### ISSUE TITLE
Implement BEMJSON notation

### ISSUE THREAD

**Issue by andre487** [bem/bem-naming#67]
Will be very helpful if there will be full BEMJSON support: 

```js
bemNaming.stringify({block: 'page', mods: {type: 'inner'}, mix: {block: 'page-404', elem: 'content', elemMods: {type: 'any'}}});
// page page_type_inner page-404__content_type_any 
```

**Comment by tadatuta** [comment]
it should be implemented as separate package which uses `bem-naming` as `bem-naming` itself is all about one entity

**Comment by Andre-487** [comment]
Can it be separate method in bem-naming? E. g. `bemNaming.fromBemJson(bemJson)`

**Comment by blond** [comment]
The `bem-naming` works with one entity (stringify object or parse string).

BEMJSON contains several entities, so it looks more like a declaration.

If you want convert BEMJSON to BEMDECL need use [bemjson-to-decl](https://github.com/tadatuta/bemjson-to-decl) package:

```js
import bemNaming from 'bem-naming';
import toDecl from 'bemjson-to-decl';

const bemjson = {
    block: 'page', 
    mods: { type: 'inner' }, 
    mix: {
        block: 'page-404',
        elem: 'content', 
        elemMods: { type: 'any' }
    }
};

const bemdecl = toDecl(bemjson);

bemdecl.map(bemNaming.stringify); // page page_type_inner page-404__content_type_any 
```

If you still have questions, reopen this issue or create a new issue.

**Comment by andre487** [comment]
Thanks! It's the solution
