### ISSUE TITLE
Provide common presets

### ISSUE THREAD

**Issue by tadatuta** [bem/bem-naming#68]
It is necessary to add `preset` option to constructor:

```js
import bemNaming from 'bem-naming';

const naming = bemNaming({ preset: 'two-dashes' });
```

Possible values:

* `origin` (by default) — Yandex convention (block__elem_mod_val)
* `two-dashes` — Harry Roberts convention (block__elem--mod_val)

**Comment by blond** [comment]
Add more details and API example, please.
