### ISSUE TITLE
Provide a way to support custom modifier separator

### ISSUE THREAD

**Issue by zxqfox** [bem/bem-naming#69]
like `block__elem_mod!!!val`

For now it's impossible to do.

Purpose is using for Harry Roberts' notation: `block__elem--mod_val`.

**Comment by Yeti-or** [comment]
I would love smth like this: `block😈elem🚬mod👯val`

**Comment by zxqfox** [comment]
How it should be pronounced? Just curious.

**Comment by Yeti-or** [comment]
block elem modifier as always.
or sex, dugs & rock n' roll

**Comment by blond** [comment]
I think we need to add `modName` and `modVal` option, and remove `mod` option.

```js
import bemNaming from 'bem-naming';

const myNaming = bemNaming({ modName: '--', modVal: '_' })
```

**Comment by blond** [comment]
Maybe we should wrap delimiters to `delimiters` field?

```js
import bemNaming from 'bem-naming';

const myNaming = bemNaming({
    delimiters: { elem: '__', modName: '--', modVal: '_' },
    wordPattern: '[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*'
});
```

**Comment by tadatuta** [comment]
I'd suggest to make `mod` polymorphic and support objects with { name: '_', value: '_' } as well as strings.
So it will be backward compatible and intuitive.

And I disagree with additional nesting with `delimiters` — there's just few opts, what's the point in grouping?
